[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  01:39:49Z

App            Version  Status  Scale  Charm        Channel  Rev  Exposed  Message
application             active      2  application             0  no       
config-server           active      1  mongodb      6/edge   173  no       Primary
mongos                  active      2  mongos                  1  no       
shard                   active      1  mongodb      6/edge   173  no       Primary

Unit              Workload  Agent  Machine  Public address  Ports            Message
application/0     active    idle   0        10.38.224.171                    
  mongos/1        active    idle            10.38.224.171                    
application/1*    active    idle   1        10.38.224.27                     
  mongos/0*       active    idle            10.38.224.27                     
config-server/0*  active    idle   2        10.38.224.187   27017-27018/tcp  Primary
shard/0*          active    idle   3        10.38.224.135   27017/tcp        Primary

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.38.224.171  juju-5e4fc8-0  ubuntu@22.04      Running
1        started  10.38.224.27   juju-5e4fc8-1  ubuntu@22.04      Running
2        started  10.38.224.187  juju-5e4fc8-2  ubuntu@22.04      Running
3        started  10.38.224.135  juju-5e4fc8-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

machine-1: 01:32:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:32:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-application-1: 01:32:07 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:32:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:32:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-application-0: 01:32:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:17 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:17 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-0: 01:32:17 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:32:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:32:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-0: 01:32:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-config-server-0: 01:33:12 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crj3ih7hmk421eh0knr0 seems to have no observers, could be removed
unit-shard-0: 01:33:13 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crj3ihfhmk421eh0knrg seems to have no observers, could be removed
unit-mongos-1: 01:33:29 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-mongos-0: 01:33:29 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-config-server-0: 01:33:46 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard shard to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726364025, 1), 'signature': {'hash': b'\\xed\\xebkP!\\xa4\\xb2\\xa3\\xe9\\xe1\\x9d\\x85M<\\x92vr\\x0e\\x89\\xaa', 'keyId': 7414676835092398103}}, 'operationTime': Timestamp(1726364025, 1)}")
unit-config-server-0: 01:33:46 ERROR unit.config-server/0.juju-log config-server:7: shard shard does not have the same auth as the config server.
unit-shard-0: 01:34:01 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crj3ihfhmk421eh0knrg seems to have no observers, could be removed
unit-shard-0: 01:34:02 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crj3ihfhmk421eh0knrg seems to have no observers, could be removed
unit-config-server-0: 01:34:08 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crj3j1vhmk421eh0knt0 seems to have no observers, could be removed
unit-config-server-0: 01:34:19 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crj3j1vhmk421eh0knt0 seems to have no observers, could be removed
unit-config-server-0: 01:34:20 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crj3j1vhmk421eh0knt0 seems to have no observers, could be removed
unit-config-server-0: 01:34:22 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crj3j1vhmk421eh0knt0 seems to have no observers, could be removed

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...