[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos/0 [idle] active: 
  mongos/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  01:38:20Z

App            Version  Status  Scale  Charm        Channel  Rev  Exposed  Message
application             active      2  application             0  no       
config-server           active      1  mongodb      6/edge   173  no       Primary
mongos                  active      2  mongos                  1  no       
shard                   active      1  mongodb      6/edge   173  no       Primary

Unit              Workload  Agent  Machine  Public address  Ports            Message
application/0*    active    idle   0        10.131.87.23                     
  mongos/0*       active    idle            10.131.87.23                     
application/1     active    idle   1        10.131.87.198                    
  mongos/1        active    idle            10.131.87.198                    
config-server/0*  active    idle   2        10.131.87.131   27017-27018/tcp  Primary
shard/0*          active    idle   3        10.131.87.83    27017/tcp        Primary

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.131.87.23   juju-fc0591-0  ubuntu@22.04      Running
1        started  10.131.87.198  juju-fc0591-1  ubuntu@22.04      Running
2        started  10.131.87.131  juju-fc0591-2  ubuntu@22.04      Running
3        started  10.131.87.83   juju-fc0591-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

machine-0: 01:31:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-application-0: 01:31:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:31:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-application-1: 01:31:23 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:31:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:31:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-0: 01:31:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:31:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-0: 01:31:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-config-server-0: 01:32:18 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjol3gm74ri105p8vng seems to have no observers, could be removed
unit-shard-0: 01:32:18 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crjol3gm74ri105p8vo0 seems to have no observers, could be removed
unit-mongos-1: 01:32:34 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-mongos-0: 01:32:34 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-config-server-0: 01:32:51 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard shard to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726450371, 1), 'signature': {'hash': b'\\x0c\\x1f\\x80\\xeb$a)\\x9fI\\x83\\xa2W\\x99}\\xccd\\xea\\x7f\\xf4\\x11', 'keyId': 7415047684043571225}}, 'operationTime': Timestamp(1726450371, 1)}")
unit-config-server-0: 01:32:51 ERROR unit.config-server/0.juju-log config-server:7: shard shard does not have the same auth as the config server.
unit-config-server-0: 01:33:07 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjoligm74ri105p8vpg seems to have no observers, could be removed
unit-shard-0: 01:33:07 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crjol3gm74ri105p8vo0 seems to have no observers, could be removed
unit-shard-0: 01:33:08 ERROR unit.shard/0.juju-log _on_secret_remove: Secret secret:crjol3gm74ri105p8vo0 seems to have no observers, could be removed
unit-config-server-0: 01:33:12 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjoligm74ri105p8vpg seems to have no observers, could be removed
unit-config-server-0: 01:33:25 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjoligm74ri105p8vpg seems to have no observers, could be removed
unit-config-server-0: 01:33:27 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjoligm74ri105p8vpg seems to have no observers, could be removed

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...